#pragma once

// Tracing
#define TRACE_INFO IOPORT_CREATE_PIN(PORTA, 1)
#define TRACE_WARN IOPORT_CREATE_PIN(PORTA, 2)
#define TRACE_ERR  IOPORT_CREATE_PIN(PORTA, 3)

// Share the trace pin
#define ALERT_OUTPUT_PIN TRACE_ERR

#define IOPORT_PRESSURE_READOUT IOPORT_CREATE_PIN(PORTB, 2)
